version: "3.3"
services:

  orchestrator:
    build:
      context: ../orchestrator
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - rabbit_mq
      - db
  db:
    image: postgres:16.1
    volumes:
      - $HOME/postgres_compose/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

  rabbit_mq:
    image: rabbitmq:3.12-management
    container_name: rabbit_mq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - $HOME/rabbitmq_data:/usr/share/rabbitmq/data

  worker:
    build:
      context: ../worker
    restart: unless-stopped
    depends_on:
      - rabbit_mq
