version: "3.5"
services:

  orchestrator:
    image: alexblacknn/orchestrator:0.0.2
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - rabbit_mq
      - db
    networks:
      - proxynet


  db:
    image: postgres:16.1
    volumes:
      - ./postgres_compose/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - proxynet

  rabbit_mq:
    image: rabbitmq:3.12-management
    container_name: rabbit_mq
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - $HOME/rabbitmq_data:/usr/share/rabbitmq/data
    networks:
      - proxynet

  worker:
    build:
      context: alexblacknn/worker:0.0.1
    restart: unless-stopped
    depends_on:
      - rabbit_mq
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network