env: "demo" #demo, prod
storage_path: "postgresql://postgres:postgres@db:5432/postgres"
redis_address: "redis:6379" # in case of redis usage insted of redis_sentinel
jaeger_url: "http://jaeger:14268/api/traces"
rabbit_mq:
  read_queue: "operation"
  write_queue: "result"
  amqp: "amqp://guest:guest@rabbit_mq:5672/"
