@startuml
!pragma layout smetana
== Запрос на Расчет ==
activate Клиент
activate Оркестратор
activate База_данных
activate Брокер_сообщений
deactivate Брокер_сообщений
activate Воркер
deactivate База_данных
Клиент -> Оркестратор: Запрос на расчет мат. выражения
alt Есть уже мат. выражение в БД
    activate База_данных
    Оркестратор -> База_данных: Получить выражение
    База_данных -> Оркестратор: uuid
    deactivate База_данных
    Оркестратор -> Клиент: uuid
else Нет мат. выражение в БД
     activate База_данных
     Оркестратор -> База_данных: Получить выражение
     База_данных -> Оркестратор: нет данных
     deactivate База_данных
     activate Брокер_сообщений
     Оркестратор -> Брокер_сообщений: Сообщение с мат.выражением
     activate База_данных
     Оркестратор -> База_данных: Записать мат.выражение с статусом process
     deactivate База_данных
    Брокер_сообщений -> Воркер: Сообщение с мат.выражением
    Воркер -> Брокер_сообщений: Сообщение с расчетным значением
    Брокер_сообщений -> Оркестратор: Сообщение с расчетным значением (асинхронно)
    activate База_данных
    Оркестратор -> База_данных: расчетное значение и его статус (асинхронно)
    deactivate База_данных
end





@enduml