env: "demo" #demo, prod
storage_path: "postgresql://postgres:postgres@db:5432/postgres"
rabbit_url_worker : "http://guest:guest@rabbit_mq:15672/api/queues/%2f/operation"
rabbit_amqp: "amqp://guest:guest@rabbit_mq:5672/"