env: "local" #demo, prod
storage_path: "postgresql://postgres:postgres@127.0.0.1:5432/postgres"
rabbit_url_worker : "http://guest:guest@localhost:15672/api/queues/%2f/operation"
rabbit_amqp: "amqp://guest:guest@localhost:5672/"