definitions:
  execution_time.Request:
    properties:
      execution_time:
        type: integer
      operation_type:
        type: string
    required:
    - execution_time
    - operation_type
    type: object
  execution_time.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  expression.Request:
    properties:
      expression:
        type: string
    required:
    - expression
    type: object
  expression.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  response.Response:
    properties:
      error:
        type: string
      result:
        type: number
      status:
        type: string
    type: object
  result.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  worker.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
externalDocs:
  description: OpenAPI
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /expression:
    post:
      consumes:
      - application/json
      description: Создает новое выражение на сервере
      parameters:
      - description: Запрос на создание выражения
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/expression.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/expression.Response'
      summary: Создание нового выражения
      tags:
      - Calculations
  /expression/{uuid}:
    get:
      consumes:
      - application/json
      description: Получает результат по указанному идентификатору из хранилища
      parameters:
      - description: Идентификатор результата
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Response'
      summary: Получение результата по идентификатору
      tags:
      - Calculations
  /monitoring/worker:
    get:
      consumes:
      - application/json
      description: Получает количество воркеров доступных для выполнения задачи
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/worker.Response'
      summary: Получение количества активных воркеров
      tags:
      - Monitoring
  /settings/execution-time:
    post:
      consumes:
      - application/json
      description: Создает новое выражение на сервере
      parameters:
      - description: Запрос на создание выражения
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/execution_time.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/execution_time.Response'
      summary: Создание нового выражения
      tags:
      - Settings
swagger: "2.0"
