definitions:
  execution_time.Request:
    properties:
      execution_time:
        example: 1
        type: integer
      operation_type:
        example: plus
        type: string
    required:
    - execution_time
    - operation_type
    type: object
  execution_time.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  expression.Request:
    properties:
      expression:
        type: string
    required:
    - expression
    type: object
  expression.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  operations.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  response.Response:
    properties:
      error:
        type: string
      result:
        type: number
      status:
        type: string
    type: object
  result.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  user_operations.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
  worker.Response:
    properties:
      id:
        type: string
      response:
        $ref: '#/definitions/response.Response'
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: This is a distributed calculation server.
  license:
    name: Apache 2.0
  title: Swagger API
  version: "1.0"
paths:
  /expression:
    post:
      consumes:
      - application/json
      description: Создает новое выражение на сервере
      parameters:
      - description: Запрос на создание выражения
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/expression.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/expression.Response'
      security:
      - BearerAuth: []
      summary: Создание нового выражения
      tags:
      - Calculations
  /expression/{uuid}:
    get:
      consumes:
      - application/json
      description: Получает результат по указанному идентификатору из хранилища
      parameters:
      - description: Идентификатор результата
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/result.Response'
      summary: Получение результата по идентификатору
      tags:
      - Calculations
  /monitoring/worker:
    get:
      consumes:
      - application/json
      description: Получает количество воркеров доступных для выполнения задачи
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/worker.Response'
      summary: Получение количества активных воркеров
      tags:
      - Monitoring
  /operations:
    get:
      consumes:
      - application/json
      description: Переход с 1 страницы на случайную не предусмотрен! Пагинация быстрая
        с поиском по индексу. В качестве курсора пустое значение для начала, потом
        скопировать ПОСЛЕДНЮЮ дату ПОЛЯ CreatedAt , например 2024-02-18T16:27:05.271813Z
      parameters:
      - default: 2
        description: Размер страницы
        in: query
        name: page_size
        type: integer
      - description: Курсор для пагинации
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/operations.Response'
            type: array
      summary: Получение операций с пагинацией
      tags:
      - Operations
  /operations/user:
    get:
      consumes:
      - application/json
      description: Переход с 1 страницы на случайную не предусмотрен! Пагинация быстрая
        с поиском по индексу. В качестве курсора пустое значение для начала, потом
        скопировать ПОСЛЕДНЮЮ дату ПОЛЯ CreatedAt , например 2024-02-18T16:27:05.271813Z
      parameters:
      - default: 2
        description: Размер страницы
        in: query
        name: page_size
        type: integer
      - description: Курсор для пагинации
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user_operations.Response'
            type: array
      security:
      - BearerAuth: []
      summary: Получение операций с пагинацией пользователя
      tags:
      - Operations
  /settings/execution-time:
    post:
      consumes:
      - application/json
      description: 'operation_type: minus, plus, mult, div. execution_time > 0'
      parameters:
      - description: Установка времени выполнения
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/execution_time.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/execution_time.Response'
      summary: Установка нового времени выполнения
      tags:
      - Settings
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
